
# Gene Expression Signatures for the Accurate Diagnosis of Peripheral T-Cell Lymphoma Entities in the Routine Clinical Practice

```{r}
#--------------------------------------------------------
# Part 1: loading packages and functions
#--------------------------------------------------------
pacman::p_load(
    GEOquery, tidyverse, ggrepel, limma, oligo, DT, pheatmap, tidyplots, affy, oligoClasses, testit, NanoStringNCTools, NanoStringDiff
)
# function is log2transformed
isLog2Transformed <- function(data) {
    qx <- as.numeric(quantile(data, c(0., 0.25, 0.5, 0.75, 0.99, 1.0), na.rm = T))
    shouldBeLogged <- (qx[5] > 100) || (qx[6] - qx[1] > 50 && qx[2] > 0)
    return(!shouldBeLogged)
}
#--------------------------------------------------------
# Part 2: Obtaining metadata and raw data
#--------------------------------------------------------

# First obtain metadata
id <- "GSE225759" # GPL4133

# creating a temp folder
if (!dir.exists(paste0(".temp/", id))) {
    dir.create(paste0(".temp/", id))
} else {
    message("Folder already exists!")
}

# Obtaining Metadata
metaff <- getGEO(id, GSEMatrix = TRUE, getGPL = FALSE, destdir = ".temp")
length(metaff)
meta <- metaff[[1]]
colnames(exprs(meta))
head(pData(meta))

# Metadata wrangling
metadata <- pData(meta) |>
    dplyr::rename(
        caseID = "case # from supplemental table9 (pmid35839444):ch1",
        nanostring = "nanosstringclass:ch1",
    ) |>
    dplyr::select(
        geo_accession,
        characteristics_ch1.5,
        supplementary_file,
        nanostring,
        caseID
    ) |>
    dplyr::rename(
        subtype = "characteristics_ch1.5"
    ) |>
    mutate(
        subtype = str_remove(subtype, "nanostringclass: "),
        subtype = str_replace_na(subtype, ""),
        nanostring = str_replace_na(nanostring, ""),
        final_subtype = stringr::str_c(subtype, nanostring)
    ) |>
    dplyr::mutate(file = str_split(supplementary_file, "/") |> map_chr(tail, 1)) |>
    select(
        geo_accession,
        supplementary_file,
        caseID,
        final_subtype, file) |>
    dplyr::mutate(final_subtype = dplyr::recode(final_subtype,
        ATLL = "ATLL",
        "PTCL-TBX21" = "PTCLTBX",
        "PTCL-GATA3" = "PTCLGATA",
        "ALCL-neg" = "ALCLneg",
        "ALCL-pos" = "ALCLpos",
        "Intermediate AITL/TBX21" = "iAITLTBX21", "Intermediate.AITL/GATA3" = "iAITLGATA3", "Intermediate AITL/GATA3" = "iAITLGATA3"
    ))

colnames(metadata)
metadata$geo_accession
##########################
## Not following this
options(download.file.method = "curl")
raw <- "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE225nnn/GSE225759/suppl/GSE225759_RAW.tar"
matrix <- "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE225nnn/GSE225759/matrix/GSE225759_series_matrix.txt.gz"
download.file(matrix, destfile = "./.temp/GSE225759.gz", method = "curl")
dir.create("./.temp", showWarnings = FALSE, recursive = TRUE)
options(GEOquery.integrate.https = FALSE)
###########################

## Download all the files in the .temp of this environment
for (i in 1:length(metadata$supplementary_file)) {
    url <- metadata$supplementary_file[i]
    destfile <- file.path(paste0(".temp/", id, "/", metadata$file[i]))
    # Download the file
    tryCatch(
        {
            download.file(url, destfile, mode = "wb", method = "curl")
        },
        error = function(e) {
            # Fallback to default method if curl fails
            download.file(url, destfile, mode = "wb")
        }
    )
    # Optional: Extract if it's a tar file
    if (grepl("\\.tar(\\.gz)?$", destfile)) {
        untar(destfile, exdir = paste0(".temp/", id))
    }
}

#####################################################
# Assuming that everything is OK (it has been normalized)

# testing subtypes, it has supplementary files links
unique(metadata$final_subtype)
datatable(metadata)

atl_ptcl_geo <- metadata |>
    filter(final_subtype %in% c("ATLL", "PTCL-TBX21", "PTCL-GATA3", "ENKTL", "AITL", "ALCL-pos", "ALCL-neg", "Intermediate AITL/TBX21", "Intermediate.AITL/GATA3", "Intermediate AITL/GATA3")) |>
    pull(geo_accession)


```


```{r}
#--------------------------------------------------------
# Part 3: Reading nanostring data
#--------------------------------------------------------
dim(metadata)
training = metadata |>
  dplyr::filter(str_detect(file, "Training"))
dataset <- readNanoStringRccSet(
  rccFiles = file.path(".temp", id, training$file))

validation = metadata |>
  dplyr::filter(str_detect(file, "Validation"), !file%in%bad_files)

dataset2 <- readNanoStringRccSet(
  rccFiles = file.path(".temp", id, validation$file))

validation2 = metadata |>
  dplyr::filter(str_detect(file, "Validation"), file%in%bad_files)

dataset3 = readNanoStringRccSet(
  rccFiles = file.path(".temp", id, validation2$file))

dim(dataset3)
dataset$targets
dataset <-createNanoStringSetFromFiles(file.path(".temp", id, metadata$file))


# Read each file individually and check feature names
feature_lists <- lapply(file.path(".temp", id, validation$file), function(f) {
  dat <- readNanoStringRccSet(rccFiles = f)
  rownames(dat)
})

# Compare all files against the first file
mismatches <- sapply(feature_lists, function(feats) !identical(feats, feature_lists[[1]]))
bad_files <- validation$file[mismatches]

print(bad_files)  # Files that don't match the first file

# nCounter normalization
norm_data <- normalize(dataset, 
                       method = "quantile", 
                       include.hk = TRUE, 
                       include.negative = FALSE)


pData(norm_data) = pData(norm_data) |>
  tibble::rownames_to_column("file") |>
  left_join(metadata, by="file") |>
  tibble::column_to_rownames("geo_accession")

table(pData(norm_data)$final_subtype)

norm_data <- log2(exprs(norm_data) + 1)

design <- model.matrix(~ 0 + factor(pData(norm_data)$final_subtype))
design
rownames(design) <- pData(norm_data)$geo_accession
colnames(design) <- levels(factor(pData(norm_data)$final_subtype))
head(design, 20)

# Make contrasts (adjust based on your comparisons)
levels(factor(pd7$atl_subtype2))
contrast.matrix <- makeContrasts(
  ATLL_vs_PTCLTBX = ATLL - PTCLTBX,
  ATLL_vs_PTCLGATA = ATLL - PTCLGATA,
  ATLL_vs_ENKTL = ATLL - ENKTL,
  ATLL_vs_AITL = ATLL - AITL,
  ATLL_vs_ALCLpos = ATLL - ALCLpos,
  ATLL_vs_ALCLneg = ATLL - ALCLneg,
  ATLL_vs_iAITLGATA = ATLL - iAITLGATA3,
  ATLL_vs_iAITLTBX = ATLL - iAITLTBX21,
  levels = design
)

fit2 <- lmFit(norm_data, design) %>%
    contrasts.fit(contrast.matrix) %>%
    eBayes()

top_probes <- topTable(fit2, number = Inf,  adjust.method = "BH", sort.by = "B", p.value = 0.01)
top_probes |>
    arrange( desc(ATLL_vs_PTCLTBX))  |>
    tibble::rownames_to_column("ID") |>
    filter(str_detect(ID, "CD5"))




### exprs(gset) <- log2(exprs(gset))
boxplot(exprs(gset),outline=FALSE)
isLog2Transformed(exprs(gset))
summary(exprs(gset)) ## we have here NAs

# Pivot Longer for manipulation
colnames(gset)
exprs_long <- exprs(gset) |> 
  as.data.frame() |> 
  tibble::rownames_to_column("ProbeID") |> 
  pivot_longer(
    cols = -ProbeID,
    names_to = "Sample", 
    values_to = "Expression",
    values_drop_na = TRUE 
  ) |>
  filter(Sample%in%atl_ptcl_geo) 

# Corrected pivot_wider syntax
exprs_wider <- exprs_long |>
  pivot_wider(
    id_cols = ProbeID,
    names_from = Sample,
    values_from = Expression
  )

fig=exprs_wider |>
  filter(ProbeID == "IL13RA1") |>
  pivot_longer(
    cols = -ProbeID,
    names_to = "Sample", 
    values_to = "Expression",
    values_drop_na = TRUE 
  ) |>
  left_join(atl_ptcl, by=c("Sample"="geo_accession")) |>
  group_by(final_subtype) |>
  summarise(
    median_expression = median(Expression, na.rm = TRUE),
    n_samples = n()
  )
  tidyplots::tidyplot(x=final_subtype, y=Expression, color=final_subtype) |>
  tidyplots::add_data_points()

print(fig)



##  Convert to matrix
exprs_matrix <- exprs_wider |>
  column_to_rownames("ProbeID") |>
  as.matrix() 
## Removing NAs rows
exprs_clean <- exprs_matrix[complete.cases(exprs_matrix), ]

exprs_clean
sum(is.na(exprs_clean)) # return 0 after removing NAs


```


```{r}
########## initial visualization
boxplot(exprs_clean,outline=FALSE)

##### Heatmap
## argument use="c" stops an error if there are any missing data points
corMatrix <- cor(exprs_clean,use="c")
pheatmap(corMatrix)    

## Include metadata
rownames(atl_ptcl) <- colnames(corMatrix)
pheatmap(corMatrix,
         annotation_col=atl_ptcl |> select(final_subtype)) 

##### PCA
## MAKE SURE TO TRANSPOSE THE EXPRESSION MATRIX

pca <- prcomp(t(exprs_clean))

# No outliers or remove them, gse <- gse[,-outlier_samples]
pca$x |>
  as.data.frame() |>
  tibble::rownames_to_column(var="row_id") |>
  left_join(atl_ptcl, by=c("row_id"="geo_accession")) |>
  tidyplots::tidyplot(x=PC1, y=PC2, color=final_subtype) |>
  tidyplots::add_data_points()

rownames(pca$x)

### Save it, but possible to modify
full_output <- cbind(fData(gset),exprs(gset))
write_csv(full_output, path="gse_full_output.csv")

# to check if there is annotation?
rownames(fData(gset))
```


```{r}
# First perform differential expression analysis to find significant probes
library(limma)

# Create design matrix based on final_subtype
design <- model.matrix(~0 + factor(atl_ptcl$final_subtype))


# remove low expressing geneS
cutoff <- median(exprs_clean)
cutoff
## TRUE or FALSE for whether each gene is "expressed" in each sample
is_expressed <- exprs_clean > cutoff
## Identify genes expressed in more than 2 samples
keep <- rowSums(is_expressed) > 2

## check how many genes are removed / retained.
table(keep)

## subset to just those expressed genes
gse <- exprs_clean[keep,]
gse
rownames(design) = atl_ptcl$geo_accession

colnames(design) <- levels(factor(atl_ptcl$final_subtype))
head(design)

# Sanity check
all(colnames(gse) == rownames(design))
colnames(gse)
rownames(gse)

# Fit linear model
fit <- lmFit(gse, design)

# Make contrasts (adjust based on your comparisons)
levels(factor(atl_ptcl$final_subtype))
contrast.matrix <- makeContrasts(
  ATLL_vs_PTCLTBX = ATLL - PTCLTBX,
  ATLL_vs_PTCLGATA = ATLL - PTCLGATA,
  ATLL_vs_ENKTL = ATLL - ENKTL,
  ATLL_vs_AITL = ATLL - AITL,
  ATLL_vs_ALCLpos = ATLL - ALCLpos,
  ATLL_vs_ALCLneg = ATLL - ALCLneg,
  ATLL_vs_iAITLGATA = ATLL - iAITLGATA3,
  ATLL_vs_iAITLTBX = ATLL - iAITLTBX21,
  levels = design
)

fit2 <- contrasts.fit(fit, contrast.matrix)
fit2 <- eBayes(fit2)
fit2

# Get significant probes (FDR < 0.01)
top_probes <- topTable(fit2, number = Inf,  adjust.method = "BH", sort.by = "B") #p.value = 0.01,
top_probes |>
    arrange( "adj.P.Val"  ) |>
    head(50)
colnames(top_probes)

ggplot(top_probes,aes(x = ATLL_vs_PTCLTBX, y=F)) + geom_point()

## change according to your needs
p_cutoff <- 0.01
fc_cutoff <- 1
topN <- 10

top_probes %>% 
  mutate(Significant = adj.P.Val < p_cutoff, abs(ATLL_vs_PTCLTBX) > fc_cutoff ) %>% 
  ggplot(aes(x = ATLL_vs_PTCLTBX, y = F, col=Significant)) + geom_point()

colnames(topTable(fit2, coef = "ATLL_vs_PTCLTBX", sort.by = "B", number = Inf))
# Example: Get logFC and B for ATLL vs iAITL-GATA
topTable(fit2, coef = "ATLL_vs_PTCLTBX", sort.by = "B", number = Inf) |>
  tibble::rownames_to_column("ID") |>
  mutate(Significant = adj.P.Val < p_cutoff, abs(logFC) > fc_cutoff )|>
  mutate(Rank = 1:n(), Label = ifelse(Rank < topN, ID,"")) %>% 
  ggplot(aes(x = logFC, y =B, col=Significant, label=Label)) + geom_point() + geom_text_repel(col="black")

library(readr)
filter(top_probes, adj.P.Val < 0.05, abs(logFC) > 1) %>%
  write_csv(path="filtered_de_results.csv")


## Use to top 20 genes for illustration
topN <- 20
##
fullr = topTable(fit2, coef = "ATLL_vs_PTCLTBX", sort.by = "B", number = Inf) |>
  tibble::rownames_to_column("ID")
fullr 
ids_of_interest <- mutate(fullr, Rank = 1:n()) %>% 
  filter(Rank < topN) %>% 
  pull(ID)
ids_of_interest
exp_heat = exprs_clean[ids_of_interest,]

# gen differences across the dataset
pheatmap(exp_heat, scale="row")

# Filter expression data for significant probes only
exprs_sig <- exprs_long %>%
  left_join(metadata, by = c("Sample" = "geo_accession")) %>%
  filter(ProbeID %in% rownames(top_probes)) |>
  filter(final_subtype =="ATLL") 

# Create the plot with statistical testing
d = exprs_sig %>%
  tidyplots::tidyplot(x = ProbeID, y = Expression) |>
  tidyplots::add_median_dot()
d 
```


```{r}
my_genes <- c("HIG2", "CA1","ETV4","FOXA1")

anno <- AnnotationDbi::select(org.Hs.eg.db, 
                              columns=c("ENSEMBL","GO"),
                              keys=my_genes,
                              keytype = "SYMBOL")
```

https://github.com/kassambara/survminer
https://sbc.shef.ac.uk/geo_tutorial/tutorial.nb.html#Introduction
